"""
Pre-trade risk checks.
Every order passes through these checks before submission.
Checks run BEFORE sending to broker -- never after.
"""
from datetime import datetime, timedelta

import numpy as np

from quanti.config import settings
from quanti.indicators import compute_atr, compute_rsi
from quanti.types import Order, OrderSide, Portfolio


class RiskChecker:
    """
    Pre-trade risk validation. All checks reject orders, never modify them.

    Unified risk path: stop-loss and ATR trailing stop are checked here
    so both live (main_live.py) and backtest (engine.py) use the same logic.
    """

    def __init__(self):
        self._recent_orders: list[tuple[str, str, datetime]] = []
        # Per-position high water mark tracking for ATR trailing stops
        self._high_water_marks: dict[str, float] = {}
        # Per-position entry date tracking for time stops
        self._entry_dates: dict[str, datetime] = {}
        # Per-position entry ATR for volatility stops
        self._entry_atr: dict[str, float] = {}

    def check_all(
        self, orders: list[Order], portfolio: Portfolio,
        market_data: "MarketData | None" = None,
        skip_exits: bool = False,
    ) -> tuple[list[Order], list[str]]:
        """
        Run all pre-trade risk checks and exit checks.

        Runs in order:
        1. Stop-loss check (flat % loss from entry)
        2. ATR trailing stop check
        3. Capital sufficiency
        4. Position limits
        5. Duplicate detection

        Args:
            orders: Incoming orders to validate.
            portfolio: Current portfolio state.
            market_data: Current market data (required for ATR stops).
            skip_exits: If True, skip exit check generation.
                        Set True when the caller (e.g., strategy's risk_check)
                        has already generated exit orders to avoid duplicates.

        Returns (approved_orders, rejections).
        approved_orders may include SELL orders generated by stop-loss/ATR checks.
        """
        approved: list[Order] = []
        rejections: list[str] = []

        # --- Exit checks: generate SELL orders for breached stops ---

        if not skip_exits:
            # 0a. Flat stop-loss
            stop_loss_pct = float(getattr(settings, 'STOP_LOSS_PCT', 0.0) or 0.0)
            if stop_loss_pct > 0:
                stop_sells = self._check_stop_loss(portfolio, stop_loss_pct)
                for s in stop_sells:
                    approved.append(s)

            # 0b. ATR trailing stop
            trailing_stop_enabled = getattr(settings, 'ATR_TRAILING_STOP_ENABLED', False)
            if trailing_stop_enabled and market_data is not None:
                atr_period = getattr(settings, 'ATR_PERIOD', 14)
                atr_mult = getattr(settings, 'ATR_TRAILING_MULTIPLIER', 2.0)
                atr_sells = self._check_atr_trailing_stop(
                    portfolio, market_data, atr_period=atr_period, atr_mult=atr_mult,
                )
                for s in atr_sells:
                    approved.append(s)

        # --- Pre-trade checks on incoming orders ---

        for order in orders:
            issues: list[str] = []

            # 1. Capital sufficiency
            cost = order.quantity * (order.price or 0)
            if cost > portfolio.cash:
                issues.append(
                    f"CAPITAL: order cost {cost:.2f} > available cash {portfolio.cash:.2f}"
                )

            # 2. Position limit
            current_positions = len(portfolio.positions)
            new_positions = current_positions
            if order.symbol not in portfolio.positions:
                new_positions += 1
            if order.side.value == "sell" and order.symbol in portfolio.positions:
                new_positions -= 1
            if new_positions > settings.MAX_POSITIONS:
                issues.append(
                    f"POSITION_LIMIT: {new_positions} would exceed max {settings.MAX_POSITIONS}"
                )

            # 3. Duplicate detection
            dup = self._check_duplicate(order)
            if dup:
                issues.append(f"DUPLICATE: {dup}")

            if issues:
                rejections.append(f"REJECTED {order.symbol} {order.side.value}: {'; '.join(issues)}")
            else:
                approved.append(order)
                self._record_order(order)

        return (approved, rejections)

    # ------------------------------------------------------------------
    # Stop-loss checks
    # ------------------------------------------------------------------

    def _check_stop_loss(
        self, portfolio: Portfolio, stop_loss_pct: float
    ) -> list[Order]:
        """
        Generate SELL orders for positions that breached stop-loss.

        Compares current price to average cost. If loss > stop_loss_pct,
        generates a market SELL for the full position.
        """
        stop_sells: list[Order] = []

        for symbol, pos in portfolio.positions.items():
            if pos.quantity <= 0:
                continue
            if pos.current_price <= 0 or pos.avg_cost <= 0:
                continue

            loss_pct = (pos.avg_cost - pos.current_price) / pos.avg_cost * 100
            if loss_pct > stop_loss_pct:
                stop_sells.append(Order(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    quantity=pos.quantity,
                    price=None,  # market order
                    order_type="market",
                    signal_ref=f'stop-loss: {loss_pct:.1f}% > {stop_loss_pct:.1f}%',
                ))

        return stop_sells

    def _check_atr_trailing_stop(
        self, portfolio: Portfolio, market_data: "MarketData",
        atr_period: int = 14, atr_mult: float = 2.0,
    ) -> list[Order]:
        """
        Generate SELL orders for positions where price has dropped below
        the ATR trailing stop level.

        Trailing stop level = high_water_mark - atr_mult * ATR(14)

        For each held position:
        1. Compute ATR from recent market data bars
        2. Update high_water_mark (highest close since entry/reset)
        3. If current price < high_water_mark - atr_mult * ATR, generate SELL
        """
        atr_sells: list[Order] = []

        for symbol, pos in portfolio.positions.items():
            if pos.quantity <= 0:
                continue

            bars = market_data.bars.get(symbol, [])
            if len(bars) < atr_period + 1:
                continue

            # Compute ATR
            atr = self._compute_atr(bars, atr_period)
            if atr is None or atr <= 0:
                continue

            # Track entry ATR for volatility stop
            if symbol not in self._entry_atr:
                self._entry_atr[symbol] = atr

            # Update high water mark
            current_close = bars[-1].close
            hwm = self._high_water_marks.get(symbol, current_close)
            if current_close > hwm:
                hwm = current_close
            self._high_water_marks[symbol] = hwm

            # RSI-based ATR multiplier tightening
            effective_mult = atr_mult
            rsi_enabled = getattr(settings, 'RSI_EXIT_ENABLED', False)
            if rsi_enabled:
                rsi_period = getattr(settings, 'RSI_PERIOD', 14)
                rsi_overbought = getattr(settings, 'RSI_OVERBOUGHT', 80)
                atr_mult_tight = getattr(settings, 'ATR_TIGHTEN_MULTIPLIER', 1.5)
                closes = np.array([b.close for b in bars], dtype=np.float64)
                rsi = self._compute_rsi(closes, rsi_period)
                if rsi is not None and rsi > rsi_overbought:
                    effective_mult = atr_mult_tight  # Tighten when overbought

            # Check trailing stop breach
            stop_level = hwm - effective_mult * atr
            if current_close < stop_level:
                atr_sells.append(Order(
                    symbol=symbol,
                    side=OrderSide.SELL,
                    quantity=pos.quantity,
                    price=None,  # market order
                    order_type="market",
                    signal_ref=f'ATR trailing stop: close={current_close:.4f} < stop={stop_level:.4f} (HWM={hwm:.4f}, ATR={atr:.4f}, mult={effective_mult})',
                ))
                # Reset HWM after exit
                self._high_water_marks.pop(symbol, None)
                self._entry_atr.pop(symbol, None)

        return atr_sells

    # ------------------------------------------------------------------
    # Indicator helpers (delegating to shared quanti.indicators)
    # ------------------------------------------------------------------

    @staticmethod
    def _compute_atr(bars: list, period: int = 14) -> float | None:
        return compute_atr(bars, period)

    @staticmethod
    def _compute_rsi(closes: np.ndarray, period: int = 14) -> float | None:
        return compute_rsi(closes, period)

    # ------------------------------------------------------------------
    # Individual checks (used by strategy.risk_check() path)
    # ------------------------------------------------------------------

    def check_capital_sufficiency(self, order: Order, cash: float) -> str | None:
        """Check if there is enough cash for this order."""
        cost = order.quantity * (order.price or 0)
        if cost > cash:
            return f"Insufficient capital: need {cost:.2f}, have {cash:.2f}"
        return None

    def check_position_limit(self, order: Order, current_symbols: set[str]) -> str | None:
        """Check if adding this position would exceed the limit."""
        new_count = len(current_symbols)
        if order.symbol not in current_symbols:
            new_count += 1
        if new_count > settings.MAX_POSITIONS:
            return f"Position limit: {new_count} > {settings.MAX_POSITIONS}"
        return None

    def _check_duplicate(self, order: Order) -> str | None:
        """Detect duplicate orders within the configurable window."""
        now = datetime.now()
        window = timedelta(seconds=settings.DUPLICATE_WINDOW_SECONDS)
        cutoff = now - window

        # Prune old entries
        self._recent_orders = [
            (sym, side, ts) for sym, side, ts in self._recent_orders
            if ts > cutoff
        ]

        for sym, side, _ts in self._recent_orders:
            if sym == order.symbol and side == order.side.value:
                return f"Similar order for {sym} {side} within {settings.DUPLICATE_WINDOW_SECONDS}s"

        return None

    def _record_order(self, order: Order) -> None:
        """Record an approved order for duplicate detection."""
        self._recent_orders.append(
            (order.symbol, order.side.value, datetime.now())
        )

    def is_instrument_valid(self, symbol: str) -> tuple[bool, str]:
        """
        Check if an instrument is still valid for trading.
        In production: query broker for instrument status.
        For now: always valid (placeholder for Phase 4 integration).
        """
        # TODO Phase 4: Query QMT for instrument status
        return (True, "")

    # ------------------------------------------------------------------
    # HWM / Entry tracking (exposed for strategy.risk_check() use)
    # ------------------------------------------------------------------

    def register_entry(self, symbol: str, entry_price: float, entry_date: datetime, entry_atr: float = 0.0) -> None:
        """Register a new position entry for trailing stop tracking."""
        self._high_water_marks[symbol] = entry_price
        self._entry_dates[symbol] = entry_date
        if entry_atr > 0:
            self._entry_atr[symbol] = entry_atr

    def register_exit(self, symbol: str) -> None:
        """Clear tracking state when a position is fully exited."""
        self._high_water_marks.pop(symbol, None)
        self._entry_dates.pop(symbol, None)
        self._entry_atr.pop(symbol, None)

    def get_high_water_mark(self, symbol: str) -> float | None:
        """Get current high water mark for a symbol."""
        return self._high_water_marks.get(symbol)

    def get_entry_date(self, symbol: str) -> datetime | None:
        """Get entry date for a symbol."""
        return self._entry_dates.get(symbol)

    def get_entry_atr(self, symbol: str) -> float | None:
        """Get entry ATR for volatility stop checks."""
        return self._entry_atr.get(symbol)
